package com.example.weatherapp.data.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.squareup.moshi.Json
import org.threeten.bp.Instant
import org.threeten.bp.ZoneId
import org.threeten.bp.ZonedDateTime

const val CURRENT_LOCATION_ID = 0

@Entity(tableName = "current_location")
data class WeatherLocation(
    val name: String,
    val country: String,
    val region: String,
    val lat: String,
    val lon: String,
    @Json(name = "timezone_id")
    val timezoneId: String,
    @Json(name = "localtime_epoch")
    val localtimeEpoch: Long
) {
    // There will be only one instance of current location, so id can be a constant and should not be autogenerated
    @PrimaryKey(autoGenerate = false)
    var id: Int = CURRENT_LOCATION_ID

    val zoneDateTime: ZonedDateTime
        get() {
            val instant = Instant.ofEpochSecond(localtimeEpoch)
            val zoneId = ZoneId.of(timezoneId)
            return ZonedDateTime.ofInstant(instant, zoneId)
        }
}